apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

bases:
- github.com/kubeflow/pipelines/manifests/kustomize/base
- github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic/minio

configMapGenerator:
- name: pipeline-install-config
  env: params.env
  behavior: merge
- name: workflow-controller-configmap
  behavior: replace
  files:
  - config

secretGenerator:
- name: mysql-secret
  env: secret.env
  behavior: merge

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines