# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Install KF
        run: |
          mkdir kubeflow
          cd kubeflow
          curl -LO https://github.com/kubeflow/kfctl/releases/download/v1.1.0/kfctl_v1.1.0-0-g9a3621e_linux.tar.gz
          tar -xvf kfctl_v1.1.0-0-g9a3621e_linux.tar.gz
          export BASE_DIR=$(echo $(pwd))
          export PATH=$PATH:$(echo $(pwd))
          export KF_NAME=kf-test
          export KF_DIR=${BASE_DIR}/${KF_NAME}
          mkdir -p ${KF_DIR}
          cd ${KF_DIR}
          kfctl -h
          
